apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: bakery-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: bakery-shop
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    appendonly yes
    dir /data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: bakery-shop
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
