apiVersion: v1
kind: Secret
metadata:
  name: bakery-secrets
  namespace: bakery-shop
type: Opaque
stringData:
  MYSQL_USER: bakery_app
  MYSQL_PASSWORD: ChangeMe_BakeryApp_123!
  JWT_SECRET: replace_with_long_random_secret
  POSTGRES_PASSWORD: Hogwarts20014709Swag???
