const en = {
  header: {
    title: 'Sunny Bakery',
    tagline: 'Warm smiles, fresh pastries, and sunshine in every order.',
    shop: 'Shop',
    admin: 'Admin',
    cart: 'Cart',
    signOut: 'Sign out',
    signInUp: 'Sign in / Sign up',
    logoAlt: 'Sunny Bakery logo',
    languageSwitchLabel: 'Language switcher'
  },
  app: {
    loadingProducts: 'Loading products...'
  },
  auth: {
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    emailOrLogin: 'Email or login',
    email: 'Email',
    signInPlaceholder: 'Admin or you@bakery.com',
    signUpPlaceholder: 'you@bakery.com',
    password: 'Password',
    passwordPlaceholder: 'At least 8 chars',
    pleaseWait: 'Please wait...',
    signIn: 'Sign in',
    signUp: 'Sign up',
    needAccount: 'Need an account? Sign up',
    haveAccount: 'Already have account? Sign in'
  },
  cart: {
    title: 'Your Cart',
    empty: 'Your cart is empty.',
    total: 'Total',
    processing: 'Processing...',
    placeOrder: 'Place order'
  },
  admin: {
    areaTitle: 'Admin area',
    areaAuth: 'Admin authentication required. Login with Admin / Ko1337Bra?',
    loginTitle: 'Admin login',
    loginHint: 'Enter admin login and password to access dashboard.',
    loginField: 'Login',
    passwordField: 'Password',
    loginButton: 'Enter admin panel',
    loginRoleError: 'This account is not an admin account.',
    ordersTitle: 'Orders',
    ordersFilterLabel: 'Orders date filter',
    lastDay: 'Last day',
    lastWeek: 'Last week',
    lastMonth: 'Last month',
    lastYear: 'Last year',
    choosePeriod: 'Choose period',
    periodFrom: 'From',
    periodTo: 'To',
    applyPeriod: 'Apply period',
    periodValidationError: 'Please select both dates.',
    ordersLoading: 'Loading orders...',
    noOrders: 'No orders for selected period.',
    orderId: 'Order ID',
    orderCustomer: 'Customer',
    orderPhone: 'Phone number',
    orderAdress: 'Adress',
    orderTotal: 'Total',
    orderStatus: 'Status',
    orderCreatedAt: 'Created at',
    totalOrders: 'Total Orders',
    totalCustomers: 'Total Customers',
    totalProducts: 'Total Products',
    revenue: 'Revenue',
    dashboardTitle: 'Bakery command center',
    dashboardSubtitle: 'Manage products in one place and open a dedicated orders workspace when you need a calmer view.',
    dashboardNote: 'Product edits stay here. Orders get their own screen.',
    sectionsTitle: 'Sections',
    productsSectionTitle: 'Products',
    productsSectionDescription: 'Edit the menu and keep the catalog fresh.',
    ordersSectionTitle: 'Orders',
    ordersSectionDescription: 'Open the dedicated orders screen with a richer overview.',
    openSection: 'Open section',
    ordersPageEyebrow: 'Orders room',
    ordersPageTitle: 'Orders that feel organized',
    ordersPageSubtitle: 'A calmer workspace for reviewing recent bakery orders.',
    ordersBack: 'Back to admin',
    productsPageTitle: 'Products that stay up to date',
    productsPageSubtitle: 'Create, edit, and review bakery items in a dedicated products workspace.',
    ordersToolbarHint: 'Use the time filters to inspect the latest bakery activity.',
    ordersEmptyHint: 'No items are waiting in this range. Try another period.',
    ordersGalleryAltPrimary: 'Fresh bakery pastries on a tray',
    ordersVisualTitle: 'Warm bakery focus',
    ordersVisualSubtitle: 'One clear visual and a slower rhythm make order review easier.',
    ordersGalleryAltSecondary: 'Cupcakes and bakery desserts on a shelf',
    ordersGalleryAltTertiary: 'Fresh bread and coffee in a cozy bakery setting',
    dashboardGalleryAltPrimary: 'Bakery cakes and pastries on a table',
    dashboardGalleryAltSecondary: 'Fresh croissants and bread in a bakery display',
    dashboardGalleryAltTertiary: 'Colorful desserts and baked goods in a cozy kitchen',
    editProduct: 'Edit product',
    addProduct: 'Add product',
    productName: 'Product name',
    description: 'Description',
    imageUrl: 'Image URL (e.g. /images/products/prd-001.jpg)',
    imageUploadButton: 'Upload image from disk',
    imageUploading: 'Uploading image...',
    imageUploadHint: 'No image uploaded yet.',
    imageUploadError: 'Failed to upload image.',
    price: 'Price',
    update: 'Update',
    create: 'Create',
    tableName: 'Name',
    tableDescription: 'Description',
    tablePrice: 'Price',
    tableImageUrl: 'Image URL',
    tableActions: 'Actions',
    edit: 'Edit',
    delete: 'Delete'
  }
};

export default en;
