const en = {
  header: {
    title: 'Sunny Bakery',
    tagline: 'Warm smiles, fresh pastries, and sunshine in every order.',
    shop: 'Shop',
    admin: 'Admin',
    cart: 'Cart',
    orders: 'Orders',
    nutrition: 'Nutrition tracker',
    signOut: 'Sign out',
    signInUp: 'Sign in / Sign up',
    logoAlt: 'Sunny Bakery logo',
    languageSwitchLabel: 'Language switcher'
  },
  app: {
    loadingProducts: 'Loading products...'
  },
  auth: {
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    emailOrLogin: 'Email or login',
    email: 'Email',
    signInPlaceholder: 'Admin or you@bakery.com',
    signUpPlaceholder: 'you@bakery.com',
    password: 'Password',
    passwordPlaceholder: 'At least 8 chars',
    pleaseWait: 'Please wait...',
    signIn: 'Sign in',
    signUp: 'Sign up',
    needAccount: 'Need an account? Sign up',
    haveAccount: 'Already have account? Sign in'
  },
  cart: {
    title: 'Your Cart',
    empty: 'Your cart is empty.',
    total: 'Total',
    processing: 'Processing...',
    placeOrder: 'Place order'
  },
  admin: {
    areaTitle: 'Admin area',
    areaAuth: 'Admin authentication required. Login with Admin / Ko1337Bra?',
    loginTitle: 'Admin login',
    loginHint: 'Enter admin login and password to access dashboard.',
    loginField: 'Login',
    passwordField: 'Password',
    loginButton: 'Enter admin panel',
    loginRoleError: 'This account is not an admin account.',
    ordersTitle: 'Orders',
    ordersFilterLabel: 'Orders date filter',
    lastDay: 'Last day',
    lastWeek: 'Last week',
    lastMonth: 'Last month',
    lastYear: 'Last year',
    choosePeriod: 'Choose period',
    periodFrom: 'From',
    periodTo: 'To',
    applyPeriod: 'Apply period',
    periodValidationError: 'Please select both dates.',
    ordersLoading: 'Loading orders...',
    noOrders: 'No orders for selected period.',
    orderId: 'Order ID',
    orderCustomer: 'Customer',
    orderPhone: 'Phone number',
    orderAdress: 'Adress',
    orderTotal: 'Total',
    orderStatus: 'Status',
    orderCreatedAt: 'Created at',
    totalOrders: 'Total Orders',
    totalCustomers: 'Total Customers',
    totalProducts: 'Total Products',
    revenue: 'Revenue',
    dashboardTitle: 'Bakery command center',
    dashboardSubtitle: 'Manage products in one place and open a dedicated orders workspace when you need a calmer view.',
    dashboardNote: 'Product edits stay here. Orders get their own screen.',
    sectionsTitle: 'Sections',
    productsSectionTitle: 'Products',
    productsSectionDescription: 'Edit the menu and keep the catalog fresh.',
    ordersSectionTitle: 'Orders',
    ordersSectionDescription: 'Open the dedicated orders screen with a richer overview.',
    openSection: 'Open section',
    metricsSectionTitle: 'Metrics',
    metricsSectionDescription: 'Inspect user activity events from web and mobile clients.',
    metricsPageTitle: 'User activity metrics',
    metricsPageSubtitle: 'Filter and review logged events across platforms and sessions.',
    metricsFiltersTitle: 'Filters',
    metricsEventType: 'Event type',
    metricsPlatform: 'Platform',
    metricsPage: 'Page',
    metricsCustomerId: 'Customer ID',
    metricsSessionId: 'Session ID',
    metricsAny: 'Any',
    metricsApplyFilters: 'Apply filters',
    metricsResetFilters: 'Reset',
    metricsLoading: 'Loading metrics...',
    metricsEmpty: 'No events match the selected filters.',
    metricsTotalEvents: 'Matched events',
    metricsColTime: 'Time',
    metricsColEvent: 'Event',
    metricsColPlatform: 'Platform',
    metricsColPage: 'Page',
    metricsColUser: 'User',
    metricsColDetails: 'Details',
    metricsProduct: 'Product',
    metricsOrder: 'Order',
    metricsSession: 'Session',
    ordersPageEyebrow: 'Orders room',
    ordersPageTitle: 'Orders that feel organized',
    ordersPageSubtitle: 'A calmer workspace for reviewing recent bakery orders.',
    ordersBack: 'Back to admin',
    productsPageTitle: 'Products that stay up to date',
    productsPageSubtitle: 'Create, edit, and review bakery items in a dedicated products workspace.',
    ordersToolbarHint: 'Use the time filters to inspect the latest bakery activity.',
    ordersEmptyHint: 'No items are waiting in this range. Try another period.',
    ordersGalleryAltPrimary: 'Fresh bakery pastries on a tray',
    ordersVisualTitle: 'Warm bakery focus',
    ordersVisualSubtitle: 'One clear visual and a slower rhythm make order review easier.',
    ordersGalleryAltSecondary: 'Cupcakes and bakery desserts on a shelf',
    ordersGalleryAltTertiary: 'Fresh bread and coffee in a cozy bakery setting',
    dashboardGalleryAltPrimary: 'Bakery cakes and pastries on a table',
    dashboardGalleryAltSecondary: 'Fresh croissants and bread in a bakery display',
    dashboardGalleryAltTertiary: 'Colorful desserts and baked goods in a cozy kitchen',
    editProduct: 'Edit product',
    addProduct: 'Add product',
    productName: 'Product name',
    description: 'Description',
    imageUrl: 'Image URL (e.g. /images/products/prd-001.jpg)',
    imageUploadButton: 'Upload image from disk',
    imageUploading: 'Uploading image...',
    imageUploadHint: 'No image uploaded yet.',
    imageUploadError: 'Failed to upload image.',
    price: 'Price',
    update: 'Update',
    create: 'Create',
    tableName: 'Name',
    tableDescription: 'Description',
    tablePrice: 'Price',
    tableImageUrl: 'Image URL',
    tableActions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    acceptOrder: 'Accept order',
    acceptingOrder: 'Accepting...',
    messagesSectionTitle: 'Messages',
    messagesSectionDescription: 'Chat with customers about their orders.',
    messagesPageTitle: 'Customer messages',
    messagesPageSubtitle: 'Open a conversation and reply from the bakery.',
    messagesConversations: 'Conversations',
    messagesLoading: 'Loading conversations...',
    messagesEmpty: 'No customer chats yet.',
    messagesNoPreview: 'No messages yet',
    messagesPick: 'Select a conversation to start messaging.',
    messagesYou: 'You',
    messagesPlaceholder: 'Write a reply...',
    messagesSend: 'Send',
    messagesSending: 'Sending...'
  },
  orders: {
    pageTitle: 'Your orders',
    pageSubtitle: 'Track status, cancel pending orders, or chat with the bakery.',
    backToShop: 'Back to shop',
    loading: 'Loading orders...',
    emptyTitle: 'No orders yet',
    emptyHint: 'Place an order from the shop to see it here.',
    total: 'Total',
    createdAt: 'Placed at',
    phone: 'Phone',
    address: 'Address',
    items: 'Items',
    cancel: 'Cancel order',
    chat: 'Chat',
    chatTitle: 'Chat with bakery',
    chatLoading: 'Loading messages...',
    chatEmpty: 'No messages yet. Say hello!',
    chatAdmin: 'Bakery',
    chatYou: 'You',
    chatPlaceholder: 'Write a message...',
    chatSend: 'Send',
    chatSending: 'Sending...',
    status: {
      PLACED: 'Placed',
      ACCEPTED: 'Accepted',
      DONE: 'Done',
      CANCELLED: 'Cancelled'
    }
  },
  nutrition: {
    pageTitle: 'Nutrients tracker',
    pageSubtitle: 'Log dishes, review macros, and track what you ate each day.',
    backToShop: 'Back to shop',
    addDish: 'Add dish',
    addDishTitle: 'Add dish',
    dishName: 'Dish name',
    dishPhoto: 'Dish photo',
    calories: 'Calories',
    proteins: 'Proteins',
    fats: 'Fats',
    carbohydrates: 'Carbohydrates',
    description: 'Description',
    save: 'Save',
    saving: 'Saving...',
    loading: 'Loading nutrition data...',
    emptyTitle: 'No dishes logged yet',
    emptyHint: 'Tap Add dish to log your first meal.',
    noChartData: 'No chart data for this period.',
    filterLabel: 'Nutrition date filter',
    last_day: 'Last day',
    last_week: 'Last week',
    last_month: 'Last month',
    customRange: 'Custom range',
    from: 'From',
    to: 'To',
    apply: 'Apply',
    periodValidationError: 'Please select a valid date range.'
  }
};

export default en;
