const ru = {
  header: {
    title: 'Sunny Bakery',
    tagline: 'Больше солнца в каждом заказе: теплая выпечка и радостная доставка.',
    shop: 'Магазин',
    admin: 'Админ',
    cart: 'Корзина',
    signOut: 'Выйти',
    signInUp: 'Вход / Регистрация',
    logoAlt: 'Логотип Sunny Bakery',
    languageSwitchLabel: 'Переключение языка'
  },
  app: {
    loadingProducts: 'Загрузка товаров...'
  },
  auth: {
    welcomeBack: 'С возвращением',
    createAccount: 'Создать аккаунт',
    emailOrLogin: 'Email или логин',
    email: 'Email',
    signInPlaceholder: 'Admin или you@bakery.com',
    signUpPlaceholder: 'you@bakery.com',
    password: 'Пароль',
    passwordPlaceholder: 'Минимум 8 символов',
    pleaseWait: 'Подождите...',
    signIn: 'Войти',
    signUp: 'Зарегистрироваться',
    needAccount: 'Нет аккаунта? Регистрация',
    haveAccount: 'Уже есть аккаунт? Войти'
  },
  cart: {
    title: 'Ваша корзина',
    empty: 'Корзина пуста.',
    total: 'Итого',
    processing: 'Обработка...',
    placeOrder: 'Оформить заказ'
  },
  admin: {
    areaTitle: 'Панель администратора',
    areaAuth: 'Требуется авторизация администратора. Вход: Admin / Ko1337Bra?',
    loginTitle: 'Вход администратора',
    loginHint: 'Введите логин и пароль администратора для доступа к панели.',
    loginField: 'Логин',
    passwordField: 'Пароль',
    loginButton: 'Войти в админ-панель',
    loginRoleError: 'Эта учетная запись не является администратором.',
    ordersTitle: 'Заказы',
    ordersFilterLabel: 'Фильтр заказов по дате',
    lastDay: 'За день',
    lastWeek: 'За неделю',
    lastMonth: 'За месяц',
    lastYear: 'За год',
    choosePeriod: 'Выбрать период',
    periodFrom: 'С',
    periodTo: 'По',
    applyPeriod: 'Применить период',
    periodValidationError: 'Выберите обе даты.',
    ordersLoading: 'Загрузка заказов...',
    noOrders: 'Нет заказов за выбранный период.',
    orderId: 'ID заказа',
    orderCustomer: 'Клиент',
    orderPhone: 'Телефон',
    orderAdress: 'Адрес',
    orderTotal: 'Сумма',
    orderStatus: 'Статус',
    orderCreatedAt: 'Создан',
    totalOrders: 'Всего заказов',
    totalCustomers: 'Всего клиентов',
    totalProducts: 'Всего товаров',
    revenue: 'Выручка',
    dashboardTitle: 'Центр управления пекарней',
    dashboardSubtitle: 'Управляйте товарами в одном месте и открывайте отдельное рабочее пространство заказов, когда нужен спокойный обзор.',
    dashboardNote: 'Изменения товаров остаются здесь. Заказы получают свой экран.',
    sectionsTitle: 'Разделы',
    productsSectionTitle: 'Товары',
    productsSectionDescription: 'Редактируйте меню и поддерживайте каталог свежим.',
    ordersSectionTitle: 'Заказы',
    ordersSectionDescription: 'Откройте отдельный экран заказов с более удобным обзором.',
    openSection: 'Открыть раздел',
    ordersPageEyebrow: 'Комната заказов',
    ordersPageTitle: 'Заказы, которые удобно разбирать',
    ordersPageSubtitle: 'Спокойное рабочее пространство для просмотра свежих заказов пекарни.',
    ordersBack: 'Назад в админку',
    productsPageTitle: 'Товары, которые легко обновлять',
    productsPageSubtitle: 'Создавайте, редактируйте и просматривайте позиции в отдельном рабочем пространстве товаров.',
    ordersToolbarHint: 'Используйте фильтры по времени, чтобы смотреть последнюю активность пекарни.',
    ordersEmptyHint: 'В этом диапазоне пока нет заказов. Попробуйте другой период.',
    ordersGalleryAltPrimary: 'Свежая выпечка на подносе',
    ordersVisualTitle: 'Теплый акцент пекарни',
    ordersVisualSubtitle: 'Один спокойный визуальный акцент помогает удобнее разбирать заказы.',
    ordersGalleryAltSecondary: 'Капкейки и десерты на полке',
    ordersGalleryAltTertiary: 'Свежий хлеб и кофе в уютной пекарне',
    dashboardGalleryAltPrimary: 'Торты и выпечка на столе',
    dashboardGalleryAltSecondary: 'Свежие круассаны и хлеб на витрине',
    dashboardGalleryAltTertiary: 'Яркие десерты и выпечка в уютной кухне',
    editProduct: 'Редактировать товар',
    addProduct: 'Добавить товар',
    productName: 'Название товара',
    description: 'Описание',
    imageUrl: 'URL изображения (например, /images/products/prd-001.jpg)',
    imageUploadButton: 'Загрузить изображение с диска',
    imageUploading: 'Загрузка изображения...',
    imageUploadHint: 'Изображение еще не загружено.',
    imageUploadError: 'Не удалось загрузить изображение.',
    price: 'Цена',
    update: 'Обновить',
    create: 'Создать',
    tableName: 'Название',
    tableDescription: 'Описание',
    tablePrice: 'Цена',
    tableImageUrl: 'URL изображения',
    tableActions: 'Действия',
    edit: 'Изменить',
    delete: 'Удалить'
  }
};

export default ru;
